### PR TITLE
AB#1851 poi changes new

### PR DESCRIPTION
**Pull request by mimran972**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Review by temalo — APPROVED** [review]
Looks good

**Review by udayansarma — APPROVED** [review]
approved by reviewer2

**Comment by mimran972** [comment]
[AB#1851](https://zmimran.visualstudio.com/05cfe636-4851-4103-ad10-e75ed7a7d44d/_workitems/edit/1851) Final merge

**Comment by mimran972** [comment]
Fixed [AB#1851](https://zmimran.visualstudio.com/05cfe636-4851-4103-ad10-e75ed7a7d44d/_workitems/edit/1851)

**Pull request merged**
